myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls)
    path('accounts/', include('accounts.urls')),
]

popplace/urls.py
from django.urls import path
from . import views
from .views import mypage

app_name='popplace'

urlpatterns = [
  path('', views.splash, name='splash'),
  path('main/', views.main, name='main'),
  path('search/', views.search, name='search'),
  path('map/', views.map, name='map'),
  path('magazine/', views.magazine, name='magazine'),
  path('mypage/', views.mypage, name='mypage'),
  path('account/login/', views.login, name='login'),
  path('signup/', views.signup, name='signup'),
  path('signup/done', views.signdone, name='signdone'),
  path('popupstore/', views.popupstore, name='popupstores'),
  path('popupstore/<int:popup_id>/', views.popupstore, name='popupstore'),
  path('popupstore/<int:popup_id>/reservation', views.popupreserv, name='popupreserv'),
  path('popupstore/<int:popup_id>/reserved',views.popupreserved, name='popupreserved'),
  path('popupstore/<int:popup_id>/review', views.popupreview, name='popupreview'),
  path('mypage/reservation_history/', views.reservation_history, name='reservation_history'),
  
]

yeougi2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accountapp.urls')),  # accountapp의 URLconf를 포함
]

yeougithon5/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from popplace import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accountapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # 로그인 관련 URL 패턴 포함
    path('', include("popplace.urls", namespace="popplace")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

popplace/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models
from django.utils import timezone

Member = get_user_model()
class Column(models.Model):
        title = models.CharField(max_length=200)
        content = models.TextField()
        created_at = models.DateTimeField(auto_now_add=True)


class Event(models.Model):
        title = models.CharField(max_length=200)
        description = models.TextField()
        start_date = models.DateTimeField()
        end_date = models.DateTimeField()
        column = models.ForeignKey(Column, on_delete=models.CASCADE, related_name='events')

class PopupStore(models.Model):
    name = models.CharField(max_length=100)
    operating_period = models.CharField(max_length=100)
    address = models.CharField(max_length=255)
    image = models.ImageField(upload_to='popup_images/')
    description = models.TextField()
    latitude = models.FloatField()  # 위도 필드
    longitude = models.FloatField()  # 경도 필드

    def __str__(self):
        return self.name


class Review(models.Model):
    popup_store = models.ForeignKey(PopupStore, on_delete=models.CASCADE)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='review_images/', null=True, blank=True)
    video = models.FileField(upload_to='review_videos/', null=True, blank=True)
    content = models.TextField()
    date = models.DateField(auto_now_add=True)
    sustainability_rating = models.IntegerField()

    def __str__(self):
        return self.title

# class Stamp(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='stamps')
    # code = models.CharField(max_length=20)
    # date_received = models.DateTimeField(auto_now_add=True)

# class Favorite(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    # popup_store = models.ForeignKey(PopupStore, on_delete=models.CASCADE)

class Popup:
    pass

class Reservation(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reservations')
    # popup = models.ForeignKey(Popup, on_delete=models.CASCADE)
    popup_store = models.ForeignKey(PopupStore, on_delete=models.CASCADE, related_name='reservations')
    date = models.DateField()
    time = models.TimeField()

    # member = models.ForeignKey(Member, on_delete=models.CASCADE, verbose_name='회원')

class ReservationHistory(models.Model):
    user = models.ForeignKey(Member, on_delete=models.CASCADE)  # ForeignKey로 Member 모델과 연결
    popup_store = models.CharField(max_length=100)
    date = models.DateField()
    time = models.TimeField()

    class Meta:
        db_table = 'reservation_history'

popplace/forms.py
from django import forms
from .models import Member, Review, Reservation



class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title','content', 'image', 'video', 'sustainability_rating']

class SearchForm(forms.Form):
    query = forms.CharField(label='검색', max_length=100)

    
class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['date','time']

popplace/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse
from .models import PopupStore, Review, Reservation
from .forms import ReviewForm, SearchForm, ReservationForm
from .models import ReservationHistory, Member  # Member 모델을 가져옴

Member = get_user_model()
# Create your views here.
def splash(request):
    return render(request, 'frontend/splash.html')

def main(request):
    return render(request, 'frontend/main.html')

def search(request):
    if request.method == 'GET':
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data.get('query')  
            results = PopupStore.objects.filter(name__icontains=query)
        else:
            results = PopupStore.objects.none()
    else:
        form = SearchForm()
        results = PopupStore.objects.none()
    
    context = {
        'form': form,
        'results': results,
    }
    return render(request, 'frontend/search.html', context)

def map(request):
    query = request.GET.get('query', '')
    popup_stores = PopupStore.objects.filter(
        Q(name__icontains=query) | Q(description__icontains=query)
    )
    data = [
        {
            'id': popup_store.id,
            'name': popup_store.name,
            'latitude': popup_store.latitude,
            'longitude': popup_store.longitude,
        }
        for popup_store in popup_stores
    ]
    return JsonResponse(data, safe=False)

def magazine(request, magazine_id):
    magazine= get_object_or_404(PopupStore,pk=magazine_id)
    return render(request, 'frontend/magazine.html',{'magazine':magazine})

def magazine(request):
    return render(request, 'frontend/magazine.html')

def mypage(request):
    return render(request, 'frontend/mypage.html')

def login(request):
    return render(request, 'frontend/login.html')

def signup(request):
    return render(request, 'frontend/signup.html')

def signdone(request):
    return render(request, 'frontend/signdone.html')

# def popupstore_list(request):
#     popups = PopupStore.objects.all()
#     context = {
#         'popups': popups,
#     }
#     return render(request, 'frontend/popupstore.html', context)

def popupstore(request, popup_id):
    popup = get_object_or_404(PopupStore, id = popup_id)
    reviews = popup.review_set.all()
    context= {
        'popup':popup,
        'reviews':reviews,
    }
    return render(request, 'frontend/popupstore.html',context)

# @login_required
def popupreserv(request,popup_id):
    popup = get_object_or_404(PopupStore, id=popup_id)
    
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            reservation = form.save(commit=False)
            reservation.popup_store = popup  # assuming Reservation model has a ForeignKey to PopupStore
            reservation.save()
            return redirect('popplace:popupreserved', popup_id=popup_id)
    else:
        form = ReservationForm()
    
    context = {
        'popup': popup,
        'form': form,
    }
    return render(request, 'frontend/popupreserv.html', context)

def popupreserved(request,popup_id):
    popup = get_object_or_404(PopupStore, id=popup_id)
    context = {'popup': popup,}
    return render(request, 'frontend/popupreserved.html', context)

def popupreview(request, popup_id):

    popup = get_object_or_404(PopupStore, id=popup_id)
    reviews = Review.objects.filter(popup_store=popup)

    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            review = form.save(commit=False)
            review.popup_store = popup
            # review.user = request.user
            review.save()
            return redirect('popplace:popupstore', popup_id=popup_id)
    else:
        form = ReviewForm()

    context = {
        'popup': popup,
        'reviews': reviews,
        'form': form,
    }
    return render(request, 'frontend/popupreview.html', context)

def category(request):
    category = request.GET.get('category')  # URL에서 카테고리 파라미터 받아오기
    popup_stores = PopupStore.objects.all()

    if category:
        popup_stores = popup_stores.filter(category=category)

    context = {
        'popup_stores': popup_stores,
        'selected_category': category,  # 선택된 카테고리를 템플릿에 전달
    }
    return render(request, 'category.html', context)



@login_required
def reservation_history(request):
    user = request.user
    try:
        member = Member.objects.get(email=user.email)  # 이메일을 사용하여 Member 객체를 가져옴
        reservations = ReservationHistory.objects.filter(user=member)  # 올바른 필드 참조
    except Member.DoesNotExist:
        reservations = []  # Member 객체가 존재하지 않으면 빈 리스트 반환

    return render(request, 'reservation_history.html', {'reservations': reservations})

@login_required
def mypage(request):
    # 현재 로그인한 사용자의 예약 내역을 가져옵니다.
    reservations = Reservation.objects.filter(user=request.user)

    context = {
        'reservations': reservations
    }
    return render(request, 'frontend/mypage.html', context)

popplace/templates/frontend/nav/nav.html
{% extends 'frontend/base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/nav.css' %}" />
{% endblock %} {% block body %}
<div class="nav">
  <a href="{% url 'popplace:main' %}">
    {% block main %}
    <svg xmlns="http://www.w3.org/2000/svg" width="33" height="29" viewBox="0 0 33 29" fill="none">
      <path
        d="M2 8.87312L16.1114 2.0881C16.2321 2.03016 16.3651 2 16.5 2C16.6349 2 16.7679 2.03016 16.8886 2.0881L31 8.87312M28.1 13.0562V24.2113C28.1 24.9509 27.7945 25.6602 27.2506 26.1832C26.7068 26.7062 25.9691 27 25.2 27H7.8C7.03087 27 6.29325 26.7062 5.74939 26.1832C5.20553 25.6602 4.9 24.9509 4.9 24.2113V13.0562"
        stroke="#C8A6FF"
        stroke-width="2.2"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </svg>
    {% endblock %}
  </a>
  <a href="{% url 'popplace:search' %}">
    {% block search %}
    <svg xmlns="http://www.w3.org/2000/svg" width="29" height="29" viewBox="0 0 29 29" fill="none">
      <path
        d="M27 27L20.9681 20.9681M20.9681 20.9681C21.9999 19.9363 22.8183 18.7115 23.3767 17.3634C23.9351 16.0153 24.2225 14.5704 24.2225 13.1113C24.2225 11.6521 23.9351 10.2073 23.3767 8.85917C22.8184 7.51109 21.9999 6.28619 20.9681 5.25442C19.9363 4.22264 18.7115 3.40419 17.3634 2.8458C16.0153 2.2874 14.5704 2 13.1113 2C11.6521 2 10.2073 2.2874 8.85917 2.8458C7.51109 3.40419 6.28619 4.22264 5.25442 5.25442C3.17065 7.33818 2 10.1644 2 13.1113C2 16.0582 3.17065 18.8844 5.25442 20.9681C7.33818 23.0519 10.1644 24.2225 13.1113 24.2225C16.0582 24.2225 18.8844 23.0519 20.9681 20.9681Z"
        stroke="#C8A6FF"
        stroke-width="2.2"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </svg>
    {% endblock %}
  </a>
  <a href="{% url 'popplace:map' %}">
    {% block map %}
    <svg xmlns="http://www.w3.org/2000/svg" width="33" height="32" viewBox="0 0 33 32" fill="none">
      <path
        d="M16.512 25.6L8.52824 15.5927C7.22144 14.2232 6.37988 12.5523 6.10157 10.7747C5.82327 8.99703 6.11967 7.18579 6.95626 5.55189C7.79285 3.91799 9.1352 2.52868 10.827 1.54576C12.5187 0.562849 14.4903 0.0267838 16.512 0C19.3146 0.0245821 21.9919 1.034 23.9576 2.80717C25.9233 4.58035 27.0173 6.97273 26.9998 9.46036C27.0009 11.6305 26.1685 13.7361 24.64 15.4298L16.512 25.6ZM16.512 2.32727C14.4038 2.34876 12.3914 3.112 10.9166 4.4494C9.4418 5.7868 8.62525 7.58903 8.64623 9.46036C8.65614 11.1682 9.3483 12.8175 10.5996 14.1149L16.512 21.5505L22.5818 13.9636C23.7356 12.6853 24.3685 11.0983 24.3779 9.46036C24.3988 7.58903 23.5823 5.7868 22.1075 4.4494C20.6327 3.112 18.6203 2.34876 16.512 2.32727Z"
        fill="#C8A6FF"
      />
      <path
        d="M16.5 11C17.8807 11 19 9.88071 19 8.5C19 7.11929 17.8807 6 16.5 6C15.1193 6 14 7.11929 14 8.5C14 9.88071 15.1193 11 16.5 11Z"
        fill="#C8A6FF"
      />
      <path
        d="M30.6429 10.6667H28.2857V13.037H30.6429V29.6296H2.35714V13.037H4.71429V10.6667H2.35714C1.73199 10.6667 1.13244 10.9164 0.690391 11.3609C0.248341 11.8055 0 12.4084 0 13.037V29.6296C0 30.2583 0.248341 30.8612 0.690391 31.3057C1.13244 31.7503 1.73199 32 2.35714 32H30.6429C31.268 32 31.8676 31.7503 32.3096 31.3057C32.7517 30.8612 33 30.2583 33 29.6296V13.037C33 12.4084 32.7517 11.8055 32.3096 11.3609C31.8676 10.9164 31.268 10.6667 30.6429 10.6667Z"
        fill="#C8A6FF"
      />
    </svg>
    {% endblock %}
  </a>
  <a href="{% url 'popplace:magazine' %}">
    {% block magazine %}
    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="27" viewBox="0 0 32 27" fill="none">
      <path
        d="M16 7.25001C17.0714 3.13803 21.1181 1.03842 29.9286 1.00001C30.0694 0.999491 30.209 1.02608 30.3392 1.07825C30.4694 1.13041 30.5878 1.20712 30.6874 1.30395C30.787 1.40078 30.8659 1.51582 30.9195 1.64243C30.9732 1.76905 31.0005 1.90474 31 2.04167V20.7917C31 21.0679 30.8871 21.3329 30.6862 21.5282C30.4852 21.7236 30.2127 21.8333 29.9286 21.8333C21.3571 21.8333 18.0458 23.5137 16 26M16 7.25001C14.9286 3.13803 10.8819 1.03842 2.07144 1.00001C1.93058 0.999491 1.79102 1.02608 1.66079 1.07825C1.53056 1.13041 1.41223 1.20712 1.31264 1.30395C1.21304 1.40078 1.13414 1.51582 1.08048 1.64243C1.02683 1.76905 0.999476 1.90474 1.00001 2.04167V20.666C1.00001 21.3092 1.40983 21.8333 2.07144 21.8333C10.6429 21.8333 13.9663 23.526 16 26M16 7.25001V26"
        stroke="#C8A6FF"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </svg>
    {% endblock %}
  </a>
  <a href="{% url 'popplace:mypage' %}">
    {% block mypage %}
    <svg xmlns="http://www.w3.org/2000/svg" width="27" height="29" viewBox="0 0 27 29" fill="none">
      <path
        d="M22.95 16.9167C24.0241 16.9167 25.0543 17.2986 25.8138 17.9784C26.5733 18.6582 27 19.5803 27 20.5417V21.4056C27 25.7278 21.3165 29 13.5 29C5.6835 29 0 25.8982 0 21.4056V20.5417C0 19.5803 0.426695 18.6582 1.18622 17.9784C1.94574 17.2986 2.97587 16.9167 4.05 16.9167H22.95ZM22.95 18.7292H4.05C3.54682 18.7292 3.06166 18.8968 2.68905 19.1995C2.31645 19.5022 2.08309 19.9182 2.03445 20.3665L2.025 20.5417V21.4056C2.025 24.6367 6.60015 27.1875 13.5 27.1875C20.1501 27.1875 24.7793 24.644 24.9696 21.6002L24.975 21.4056V20.5417C24.975 20.0913 24.7877 19.657 24.4495 19.3235C24.1114 18.99 23.6466 18.7812 23.1458 18.7376L22.95 18.7292ZM13.5 0C14.5637 -1.41872e-08 15.617 0.187527 16.5997 0.551873C17.5825 0.91622 18.4754 1.45025 19.2276 2.12348C19.9797 2.7967 20.5764 3.59593 20.9834 4.47555C21.3905 5.35516 21.6 6.29792 21.6 7.25C21.6 8.20208 21.3905 9.14484 20.9834 10.0245C20.5764 10.9041 19.9797 11.7033 19.2276 12.3765C18.4754 13.0497 17.5825 13.5838 16.5997 13.9481C15.617 14.3125 14.5637 14.5 13.5 14.5C11.3517 14.5 9.29148 13.7362 7.77244 12.3765C6.25339 11.0169 5.4 9.17282 5.4 7.25C5.4 5.32718 6.25339 3.48311 7.77244 2.12348C9.29148 0.763837 11.3517 2.86522e-08 13.5 0ZM13.5 1.8125C11.8888 1.8125 10.3436 2.38538 9.20433 3.40511C8.06504 4.42484 7.425 5.80789 7.425 7.25C7.425 8.69211 8.06504 10.0752 9.20433 11.0949C10.3436 12.1146 11.8888 12.6875 13.5 12.6875C15.1112 12.6875 16.6564 12.1146 17.7957 11.0949C18.935 10.0752 19.575 8.69211 19.575 7.25C19.575 5.80789 18.935 4.42484 17.7957 3.40511C16.6564 2.38538 15.1112 1.8125 13.5 1.8125Z"
        fill="#C8A6FF"
      />
    </svg>
    {% endblock %}
  </a>
</div>
{% endblock %}

popplace/templates/frontend/nav/nav_magazine.html
{% extends 'frontend/nav/nav.html' %} {% block magazine %}
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="27" viewBox="0 0 32 27" fill="none">
  <path
    d="M16 7.25001C17.0714 3.13803 21.1181 1.03842 29.9286 1.00001C30.0694 0.999491 30.209 1.02608 30.3392 1.07825C30.4694 1.13041 30.5878 1.20712 30.6874 1.30395C30.787 1.40078 30.8659 1.51582 30.9195 1.64243C30.9732 1.76905 31.0005 1.90474 31 2.04167V20.7917C31 21.0679 30.8871 21.3329 30.6862 21.5282C30.4852 21.7236 30.2127 21.8333 29.9286 21.8333C21.3571 21.8333 18.0458 23.5137 16 26M16 7.25001C14.9286 3.13803 10.8819 1.03842 2.07144 1.00001C1.93058 0.999491 1.79102 1.02608 1.66079 1.07825C1.53056 1.13041 1.41223 1.20712 1.31264 1.30395C1.21304 1.40078 1.13414 1.51582 1.08048 1.64243C1.02683 1.76905 0.999476 1.90474 1.00001 2.04167V20.666C1.00001 21.3092 1.40983 21.8333 2.07144 21.8333C10.6429 21.8333 13.9663 23.526 16 26M16 7.25001V26"
    stroke="#9151F9"
    stroke-width="2"
    stroke-linecap="round"
    stroke-linejoin="round"
  />
</svg>
{% endblock %}

popplace/templates/frontend/nav/nav_main.html
{% extends 'frontend/nav/nav.html' %} {% block main %}
<svg xmlns="http://www.w3.org/2000/svg" width="33" height="29" viewBox="0 0 33 29" fill="none">
  <path
    d="M2 8.87312L16.1114 2.0881C16.2321 2.03016 16.3651 2 16.5 2C16.6349 2 16.7679 2.03016 16.8886 2.0881L31 8.87312M28.1 13.0562V24.2113C28.1 24.9509 27.7945 25.6602 27.2506 26.1832C26.7068 26.7062 25.9691 27 25.2 27H7.8C7.03087 27 6.29325 26.7062 5.74939 26.1832C5.20553 25.6602 4.9 24.9509 4.9 24.2113V13.0562"
    stroke="#9151F9"
    stroke-width="2.2"
    stroke-linecap="round"
    stroke-linejoin="round"
  />
</svg>
{% endblock %}

popplace/templates/frontend/nav/nav_map.html
{% extends 'frontend/nav/nav.html' %} {% block map %}
<svg xmlns="http://www.w3.org/2000/svg" width="33" height="32" viewBox="0 0 33 32" fill="none">
  <path
    d="M16.512 25.6L8.52824 15.5927C7.22144 14.2232 6.37988 12.5523 6.10157 10.7747C5.82327 8.99703 6.11967 7.18579 6.95626 5.55189C7.79285 3.91799 9.1352 2.52868 10.827 1.54576C12.5187 0.562849 14.4903 0.0267838 16.512 0C19.3146 0.0245821 21.9919 1.034 23.9576 2.80717C25.9233 4.58035 27.0173 6.97273 26.9998 9.46036C27.0009 11.6305 26.1685 13.7361 24.64 15.4298L16.512 25.6ZM16.512 2.32727C14.4038 2.34876 12.3914 3.112 10.9166 4.4494C9.4418 5.7868 8.62525 7.58903 8.64623 9.46036C8.65614 11.1682 9.3483 12.8175 10.5996 14.1149L16.512 21.5505L22.5818 13.9636C23.7356 12.6853 24.3685 11.0983 24.3779 9.46036C24.3988 7.58903 23.5823 5.7868 22.1075 4.4494C20.6327 3.112 18.6203 2.34876 16.512 2.32727Z"
    fill="#9151F9"
  />
  <path
    d="M16.5 11C17.8807 11 19 9.88071 19 8.5C19 7.11929 17.8807 6 16.5 6C15.1193 6 14 7.11929 14 8.5C14 9.88071 15.1193 11 16.5 11Z"
    fill="#9151F9"
  />
  <path
    d="M30.6429 10.6667H28.2857V13.037H30.6429V29.6296H2.35714V13.037H4.71429V10.6667H2.35714C1.73199 10.6667 1.13244 10.9164 0.690391 11.3609C0.248341 11.8055 0 12.4084 0 13.037V29.6296C0 30.2583 0.248341 30.8612 0.690391 31.3057C1.13244 31.7503 1.73199 32 2.35714 32H30.6429C31.268 32 31.8676 31.7503 32.3096 31.3057C32.7517 30.8612 33 30.2583 33 29.6296V13.037C33 12.4084 32.7517 11.8055 32.3096 11.3609C31.8676 10.9164 31.268 10.6667 30.6429 10.6667Z"
    fill="#9151F9"
  />
</svg>
{% endblock %}

popplace/templates/frontend/nav/nav_mypage.html
{% extends 'frontend/nav/nav.html' %} {% block mypage %}
<svg xmlns="http://www.w3.org/2000/svg" width="27" height="29" viewBox="0 0 27 29" fill="none">
  <path
    d="M22.95 16.9167C24.0241 16.9167 25.0543 17.2986 25.8138 17.9784C26.5733 18.6582 27 19.5803 27 20.5417V21.4056C27 25.7278 21.3165 29 13.5 29C5.6835 29 0 25.8982 0 21.4056V20.5417C0 19.5803 0.426695 18.6582 1.18622 17.9784C1.94574 17.2986 2.97587 16.9167 4.05 16.9167H22.95ZM22.95 18.7292H4.05C3.54682 18.7292 3.06166 18.8968 2.68905 19.1995C2.31645 19.5022 2.08309 19.9182 2.03445 20.3665L2.025 20.5417V21.4056C2.025 24.6367 6.60015 27.1875 13.5 27.1875C20.1501 27.1875 24.7793 24.644 24.9696 21.6002L24.975 21.4056V20.5417C24.975 20.0913 24.7877 19.657 24.4495 19.3235C24.1114 18.99 23.6466 18.7812 23.1458 18.7376L22.95 18.7292ZM13.5 0C14.5637 -1.41872e-08 15.617 0.187527 16.5997 0.551873C17.5825 0.91622 18.4754 1.45025 19.2276 2.12348C19.9797 2.7967 20.5764 3.59593 20.9834 4.47555C21.3905 5.35516 21.6 6.29792 21.6 7.25C21.6 8.20208 21.3905 9.14484 20.9834 10.0245C20.5764 10.9041 19.9797 11.7033 19.2276 12.3765C18.4754 13.0497 17.5825 13.5838 16.5997 13.9481C15.617 14.3125 14.5637 14.5 13.5 14.5C11.3517 14.5 9.29148 13.7362 7.77244 12.3765C6.25339 11.0169 5.4 9.17282 5.4 7.25C5.4 5.32718 6.25339 3.48311 7.77244 2.12348C9.29148 0.763837 11.3517 2.86522e-08 13.5 0ZM13.5 1.8125C11.8888 1.8125 10.3436 2.38538 9.20433 3.40511C8.06504 4.42484 7.425 5.80789 7.425 7.25C7.425 8.69211 8.06504 10.0752 9.20433 11.0949C10.3436 12.1146 11.8888 12.6875 13.5 12.6875C15.1112 12.6875 16.6564 12.1146 17.7957 11.0949C18.935 10.0752 19.575 8.69211 19.575 7.25C19.575 5.80789 18.935 4.42484 17.7957 3.40511C16.6564 2.38538 15.1112 1.8125 13.5 1.8125Z"
    fill="#9151F9"
  />
</svg>
{% endblock %}

popplace/templates/frontend/nav/nav_search.html
{% extends 'frontend/nav/nav.html' %} {% block search %}
<svg xmlns="http://www.w3.org/2000/svg" width="29" height="29" viewBox="0 0 29 29" fill="none">
  <path
    d="M27 27L20.9681 20.9681M20.9681 20.9681C21.9999 19.9363 22.8183 18.7115 23.3767 17.3634C23.9351 16.0153 24.2225 14.5704 24.2225 13.1113C24.2225 11.6521 23.9351 10.2073 23.3767 8.85917C22.8184 7.51109 21.9999 6.28619 20.9681 5.25442C19.9363 4.22264 18.7115 3.40419 17.3634 2.8458C16.0153 2.2874 14.5704 2 13.1113 2C11.6521 2 10.2073 2.2874 8.85917 2.8458C7.51109 3.40419 6.28619 4.22264 5.25442 5.25442C3.17065 7.33818 2 10.1644 2 13.1113C2 16.0582 3.17065 18.8844 5.25442 20.9681C7.33818 23.0519 10.1644 24.2225 13.1113 24.2225C16.0582 24.2225 18.8844 23.0519 20.9681 20.9681Z"
    stroke="#9151F9"
    stroke-width="2.2"
    stroke-linecap="round"
    stroke-linejoin="round"
  />
</svg>
{% endblock %}